name: build-extension-zip
on:
  workflow_dispatch:
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip extension contents
        run: |
          cd extension
          zip -r -X ../extension.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: extension.zip
